### ISSUE TITLE
Issue with HSTS Preload Detection in Vercel Using vercel.json

### ISSUE THREAD

**Issue by Music47ell** [zeit/now#10964]
When configuring security headers using the `vercel.json` file in my website, it seems that HSTS preload detection by hstspreload.org is not recognizing that the `Strict-Transport-Security` header is set and configured properly.

### Environment
- https://github.com/Music47ell/News47ell/blob/main/vercel.json#L20-L23 

### Expected Behavior
Hstspreload.org should detect and acknowledge that the `Strict-Transport-Security` header is properly set and configured through the `vercel.json` file.

### Actual Behavior
Hstspreload.org does not recognize the proper configuration of the `Strict-Transport-Security` header, even though it is set correctly in the `vercel.json` file.

### Test Results:

https://hstspreload.org/?domain=news47ell.com

- Error: No includeSubDomains directive
- Error: No preload directive

**Comment by trek** [comment]
Hello @Music47ell,

Please check out this post https://vercel.community/t/resolving-ip-blocking-issues/171 for resolving issues like this.

**Comment by eric-burel** [comment]
Hi @trek, facing the same issue with the same error, I didn't find a solution in the link you've shared.
As far as I can tell,  the problem is that the header is not set properly during redirections from "https://yourwebsite.com" to "https://www.yourwebsite.com". Since hstspreload.org works using a domain, I suspect they send a request to the top-level domain and not "www", so they have the wrong headers.

![image](https://github.com/user-attachments/assets/fdb94d29-3774-452f-8d81-82464d486871)

When accessing the "www" subdomain, my vercel.json config is respected.

![image](https://github.com/user-attachments/assets/03a41f80-c9c7-441a-9346-f15fae24a1f6)

**Comment by necdetsanli** [comment]
I'm experiencing the same issue. Is there any solution?
