### ISSUE TITLE
Vite and SvelteKit projects timeout After 300 seconds when using `vercel dev`

### ISSUE THREAD

**Issue by trek** [zeit/now#12581]
If you're still encountering this today it's a different root cause than the [issue from 2022](https://github.com/vercel/vercel/issues/8121).

Vite does not respect setting the port with an environment variable (https://github.com/vitejs/vite/issues/5280). While not quite _a_ standard it's essentially what every other framework is doing and how `vercel dev` does proxying from its development sever to the framework's development server.

`sveltekit` started to experience this when it switched over to using `vite` under the hood.

We have an automatic fix for this on our roadmap but until then you can resolve this by adding

```
server: {
  port: process.env.PORT
},
```

to your `vite.config.js` file.

I'll link this issue to our internal card so we can report back when it's done.

**Comment by magnuslundin** [comment]
I have an authentication solution in my SvelteKit-project with predefined callbackUrls. 

Here’s the situation:

- **Setting the server port to** `process.env.PORT` in `vite.config.ts`: This results in the callbackUrl using the "internal" (often five-digit) port, causing a mismatch with the authentication solution. I this case the Vercel CLI works as it should.
- **Hardcoding the server port in** `vite.config.ts`: This resuls in a correct callbackUrl, but the Vercel CLI times out.

@trek When this issue is resolved, will it address my problem above? 

If not, and there’s some simple configuration setting to resolve this, any guidance would be greatly appreciated :)

**Comment by trek** [comment]
@magnuslundin we'd still use an autogenerated port, so this would not resolve your issue, no. You might need to use `process.env.PORT`

**Comment by magnuslundin** [comment]
> @magnuslundin we'd still use an autogenerated port, so this would not resolve your issue, no. You might need to use `process.env.PORT`

Thank you for the quick reply!
Auth.js was automatically picking up the autogenerated port for the callbacks. I was able to resolve it by defining the correct one via an `redirectProxyUrl` option (if someone else has a similar issue). Finally my dev-environment is working.
Sorry for  confusing the issues.

**Comment by rob-balfre** [comment]
Having a similar issue here using `vercel dev` with sveltekit and vercel postgres.

I've just hacked it with 
`bash -c 'while true; do vercel dev; sleep 1; done'`

Would love a proper solution though
