### ISSUE TITLE
Issue with flask deployment

### ISSUE THREAD

**Issue by Judimax** [zeit/now#8358]
### Discussed in https://github.com/vercel/vercel/discussions/8348

<div type='discussions-op-text'>

<sup>Originally posted by **MichaelOdumosu57** August  8, 2022</sup>

## Expected Behavior

* I should be able to deploy  the flask app to vercel and it should work sucessfully. 

## Current Behavior

I get these errors
![1659959767543](https://user-images.githubusercontent.com/21322737/183413350-7aad7f3f-06ee-4503-b778-48abffc59f1e.png)
![1659959739463](https://user-images.githubusercontent.com/21322737/183413355-2fbd2629-dda7-410b-ba34-a8d9b51c943d.png)

## Possible Solution

* I need guidance to help vercel treat my app not as a serverless function but a wsgi app

## Steps to Reproduce

1. update vercel.json
```json
{
  "version": 2,
  "public":true,
  "builds": [
      {
          "src": "index.py",
          "use": "@vercel/python"
      }
  ],
  "routes": [
      {
          "src": "/(.*)",
          "dest": "index.py"
      }
  ]
}
```
2. npx vercel deploy
3.
4.

## Environment
|property|value|data|
|:------|:------:|------|
|Vercel CLI| v27.3.7||

|local python env|3.10.6||
|vercel python|@vercel/python||
|flask|2.2.1||
||||

</div>

**Comment by andymckay** [comment]
Here's an example of how to do that: 

https://github.com/andymckay/test-vercel-flask

After deploying this to vercel, a path of `/` returns `Hello world`. You could possibly use `build` but given the amount of warnings it generates, if you can avoid it and just put your code in `api` that's easier.

Please note the warnings around using `routes`: https://vercel.com/docs/project-configuration#legacy/routes

Note that I used an older version of Flask, because of an error that it was returning.

Hope that helps.
