### ISSUE TITLE
Bug: Website downloads a file if using revalidate in NextJS13

### ISSUE THREAD

**Issue by baron1000** [zeit/now#8840]
If you refresh a webpage that is using the app directory and revalidate in Next JS 13, the web browser will download a file that seems to be the cache that Vercel keeps each revalidation of the website. Please fix this bug! On Chrome, you will get it even when typing the URL into the bar if you have another instance if the website in another tab. 
<img width="1440" alt="Screen Shot 2022-11-02 at 4 19 23 PM" src="https://user-images.githubusercontent.com/117322036/199620294-04a9b1ef-b2a8-41b2-a4a3-322d9f7f5549.png">

**Comment by andymckay** [comment]
Thanks for this report @baron1000. This repository tends to be about the deployment and building of sites on vercel and I think this issue is about Next.js, although I might be wrong 😄  The repo for that is https://github.com/vercel/next.js

Also the team might ask for the simplest possible reproduction or example to help debug it, the new issue template asks for quite a lot of information: https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&template=1.bug_report.yml which is why I don't want to transfer this issue over as is.

**Comment by andymckay** [comment]
Closing based on the last comment, but we can re-open if I've got this wrong.
