### ISSUE TITLE
Please help me with login.

### ISSUE THREAD

**Issue by dawebmastaa** [zeit/now#9657]
### Discussed in https://github.com/vercel/vercel/discussions/9612

<div type='discussions-op-text'>

<sup>Originally posted by **AdvitSingh5** March  7, 2023</sup>
I want to deploy my project. 
Please help me deploy it. 
I am having issues with login.
I am trying with Github login, it asks for phone no. when i give it, it says no. is associated with a vercel account.
ok.
but i try with the normal mail. 
and it again asks for the same thing. 
then it says try again later after 1 min 
why? 
please help.</div>

Is this some kind of joke?! The 'VP of Developer Experience' tells a user of their service, instead of actually HELPING the person, to contact 'support', and then gives a link to a page that tells you to sign in to get support. Hello???? He was not able to sign in, which was the problem in the first place. How many years of college do I need to become this clueless? Your 'developer experience' is a nightmare. Why can't we log in without a phone number?!?!?!?! I didn't give one to get my account.

**How can people log in without a phone number?!?!?!?!?!**

**Comment by mutaharIU** [comment]
your issue with Github login, it's possible that you might have used a different email address when setting up your Vercel account, which is why you're encountering problems with login. You might want to double-check the email address associated with your Vercel account and use that email address when logging in with Github.

As for the issue with the phone number, it's possible that Vercel requires a phone number for security purposes, but it's also possible to log in without a phone number. You might want to try logging in again without providing a phone number and see if that works. If you're still encountering problems, you might want to contact Vercel support for assistance.

In terms of contacting Vercel support, you can visit their support page (https://vercel.com/support) and click on the "Get Help" button to access their support form. If you're not able to sign in to your account to access the support form, you can try contacting them through their social media channels or through their community forums.

I hope this helps you

**Comment by trek** [comment]
Hi @dawebmastaa,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
