### ISSUE TITLE
Specify project Id in vercel pull commands

### ISSUE THREAD

**Issue by jakeleventhal** [zeit/now#9986]
### Discussed in https://github.com/vercel/vercel/discussions/9985

<div type='discussions-op-text'>

<sup>Originally posted by **jakeleventhal** May 19, 2023</sup>
### Idea

It would be nice for local development to have a `--project-id` argument that could be passed in. then whenever a developer wants to pull from vercel, they dont have to go through the series of questions about project name, org, etc. As long as they are authenticated via cli and have access to a project, pulling via a project id should just work. What currently works now is passing in a token, but that is either org-specific or user-specific. there should be one command that all developers can run so tooling can be committed to git, and let the cli handle the authentication</div>

Ideal command example:
```bash
npx vercel pull --yes --project-id="myprojectid"

**Comment by jakeleventhal** [comment]
Solution i have tried is having a bash script in each project for my repo that looks like this (but this is not ideal)
```bash
#!/bin/bash

# Check if .vercel/project.json exists
if [ ! -f .vercel/project.json ]; then
  # Create the file
  mkdir -p .vercel
  echo '{
    "orgId": "myteamorgid",
    "projectId": "myteamprojectid"
  }' > .vercel/project.json
fi

# Run npx vercel pull
npx vercel pull --yes
```

**Comment by elliottsj** [comment]
I learned that you can alternatively set `VERCEL_ORG_ID` and `VERCEL_PROJECT_ID` as environment variables.

See also https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

**Comment by jakeleventhal** [comment]
This doesn't really solve the problem. you still end up with the same issue of needing to have these values stored locally somewhere

**Comment by schm-dt** [comment]
+1. I am struggling to workout how to correctly pull from vercel in CI when I do not already have the project settings committed to the repo (because my repo should not be tied to one project). My project is scaffold-ed via terraform so ideally I could provide the project id that is outputted from terraform to this `vercel pull` command.

**Comment by jamiter** [comment]
If you're ok with it being the project name instead of the id then you can use `vercel link`, because it accepts a `--project` option to specify the project name:

```bash
vercel link --project foo --yes
```

See https://vercel.com/docs/cli/link#project

I use it to first link the project and then pull the env:

```bash
vercel link --project foo --yes && vercel env pull ./.env --yes
```

You can add that to a package.json script or in my case an nx project target:

```cson
{
  // ...
  "targets": {
    "vercel-link": {
      "executor": "nx:run-commands",
      "options": {
        "commands": ["vercel link --project foo --yes"],
        "cwd": "apps/my-app"
      }
    },
    "pull-env": {
      "dependsOn": ["vercel-link"],
      "executor": "nx:run-commands",
      "options": {
        "commands": ["vercel env pull ./.env --yes"],
        "cwd": "apps/my-app"
      }
    }
  }
}
```

After linking you can still use `pull`, but that might not even be necessary in most cases.

**Comment by trek** [comment]
Hi @jakeleventhal,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
